Fix deprecation warning
AssertionError: [DEPRECATION WARNING]: Setting verbosity before the arg sub command is
deprecated, set the verbosity after the sub command. This feature will be
removed from ansible-core in version 2.13. Deprecation warnings can be disabled
by setting deprecation_warnings=False in ansible.cfg.

No-Issue