Fix insights dev mode ui failing to write /hub/app/node_modules/.cache (#1063)
* swagger_ui: remove container_name to fix clashes when using DEV_IMAGE_SUFFIX

    ERROR: for swagger-ui  Cannot create container for service swagger-ui: Conflict. The container name "/swagger_ui_container" is already in use by container "ecabb771316cbcdc7310a2329ceda2e9a38680f998f45a4e3fd9332d973b1377". You have to remove (or rename) that container to be able to reuse that name.
    ERROR: Encountered errors while bringing up the project.

* dev ui /hub/app/node_modules: mount as tmpfs, to let npm write .cache

to fix

    ui_1              | [webpack-cli] [Error: ENOENT: no such file or directory, mkdir '/hub/app/node_modules/.cache'] {
    ui_1              |   errno: -2,
    ui_1              |   code: 'ENOENT',
    ui_1              |   syscall: 'mkdir',
    ui_1              |   path: '/hub/app/node_modules/.cache'
    ui_1              | }
    ui_1              | npm ERR! code ELIFECYCLE
    ui_1              | npm ERR! errno 2
    ui_1              | npm ERR! ansible-hub-ui@0.1.0 start: `NODE_ENV=development webpack serve --host 0.0.0.0 --config config/insights.dev.webpack.config.js`
    ui_1              | npm ERR! Exit status 2

No-Issue