swagger_ui: remove container_name to fix clashes when using DEV_IMAGE_SUFFIX
    ERROR: for swagger-ui  Cannot create container for service swagger-ui: Conflict. The container name "/swagger_ui_container" is already in use by container "ecabb771316cbcdc7310a2329ceda2e9a38680f998f45a4e3fd9332d973b1377". You have to remove (or rename) that container to be able to reuse that name.
    ERROR: Encountered errors while bringing up the project.