Fix namespace logos on s3 (#1807)
* Fix namespace logos on S3

Issue: AAH-2575

* Fix deprecation warning

AssertionError: [DEPRECATION WARNING]: Setting verbosity before the arg sub command is
deprecated, set the verbosity after the sub command. This feature will be
removed from ansible-core in version 2.13. Deprecation warnings can be disabled
by setting deprecation_warnings=False in ansible.cfg.

No-Issue

* Updated proxy for tests
Issue: AAH-2575

* Copy the new proxy script to the oci profile path.

No-Issue

Signed-off-by: James Tanner <tanner.jc@gmail.com>

* Add workaround for keycloak issues.

No-Issue

Signed-off-by: James Tanner <tanner.jc@gmail.com>

* Add another workaround for keycloak.

No-Issue

Signed-off-by: James Tanner <tanner.jc@gmail.com>

---------

Signed-off-by: James Tanner <tanner.jc@gmail.com>
Co-authored-by: Brian McLaughlin <bmclaugh@redhat.com>
Co-authored-by: James Tanner <tanner.jc@gmail.com>