Fix schema view
Currently `/pulp/api/v3/` breaks with:
```
AssertionError: Expected view UserViewSet to be called with a URL keyword argument named "pk".
```

No-Issue