dev/: use UID, GID instead of hardcoding 1000; drop USER_ID
the problem: running as a user with uid=1001 and owning src/,
the dev environment doesn work, failing with

    error: could not create 'galaxy_ng.egg-info': Permission denied

or

    running egg_info
    error: [Errno 13] Permission denied

because the docker files assume uid=1000 and gid=1000 for the galaxy user inside the container

No-Issue