Pin click==7.1.2, click>=8.0.0 req py38 (#774)
pulpcore uses 'rq' which uses 'click'.

click version 8.0.0 or higher don't work with
python < 3.8 and we currently use python~=3.6

If click>=8.0.0 is used with python 3.6. it will
eventually raise an exception like:

ValueError: 'default' must be a list when 'multiple' is true.

See https://pulp.plan.io/issues/8744

Issue: AAH-637